from core.base.button import Button

# This file was automatically generated by tools/button_extract.py.
# Do not modify it manually.

BTN_SEED_SELECT_POPUP_RIGHT = Button(area={'qq': (511, 608, 524, 636), 'wechat': (511, 608, 524, 636)}, color={'qq': (226, 206, 123), 'wechat': (226, 206, 123)}, button={'qq': (511, 608, 524, 636), 'wechat': (511, 608, 524, 636)}, file={'qq': 'templates/qq/btn/BTN_SEED_SELECT_POPUP_RIGHT.png', 'wechat': 'templates/qq/btn/BTN_SEED_SELECT_POPUP_RIGHT.png'}, name='BTN_SEED_SELECT_POPUP_RIGHT')
BTN_STEAL_TOTAL = Button(area={'qq': (432, 274, 447, 290), 'wechat': (432, 274, 447, 290)}, color={'qq': (240, 179, 47), 'wechat': (240, 179, 47)}, button={'qq': (432, 274, 447, 290), 'wechat': (432, 274, 447, 290)}, file={'qq': 'templates/qq/btn/BTN_STEAL_TOTAL.png', 'wechat': 'templates/qq/btn/BTN_STEAL_TOTAL.png'}, name='BTN_STEAL_TOTAL')
BTN_BACKGROUND_TREE = Button(area={'qq': (178, 285, 198, 344), 'wechat': (178, 285, 198, 344)}, color={'qq': (97, 157, 105), 'wechat': (97, 157, 105)}, button={'qq': (178, 285, 198, 344), 'wechat': (178, 285, 198, 344)}, file={'qq': 'templates/qq/btn/btn_background_tree.png', 'wechat': 'templates/qq/btn/btn_background_tree.png'}, name='btn_background_tree')
BTN_BATCH_SELL = Button(area={'qq': (325, 867, 430, 901), 'wechat': (325, 867, 430, 901)}, color={'qq': (178, 196, 72), 'wechat': (178, 196, 72)}, button={'qq': (325, 867, 430, 901), 'wechat': (325, 867, 430, 901)}, file={'qq': 'templates/qq/btn/btn_batch_sell.png', 'wechat': 'templates/qq/btn/btn_batch_sell.png'}, name='btn_batch_sell')  # 批量出售
BTN_CLAIM = Button(area={'qq': (247, 619, 293, 644), 'wechat': (247, 619, 293, 644)}, color={'qq': (189, 199, 108), 'wechat': (189, 199, 108)}, button={'qq': (247, 619, 293, 644), 'wechat': (247, 619, 293, 644)}, file={'qq': 'templates/qq/btn/btn_claim.png', 'wechat': 'templates/qq/btn/btn_claim.png'}, name='btn_claim')
BTN_CLAIM_TASK = Button(area={'qq': (416, 476, 454, 497), 'wechat': (416, 476, 454, 497)}, color={'qq': (181, 195, 90), 'wechat': (181, 195, 90)}, button={'qq': (416, 476, 454, 497), 'wechat': (416, 476, 454, 497)}, file={'qq': 'templates/qq/btn/btn_claim_task.png', 'wechat': 'templates/qq/btn/btn_claim_task.png'}, name='btn_claim_task')
BTN_CLAIM_YELLOW = Button(area={'qq': (356, 750, 405, 775), 'wechat': (356, 750, 405, 775)}, color={'qq': (222, 194, 140), 'wechat': (222, 194, 140)}, button={'qq': (356, 750, 405, 775), 'wechat': (356, 750, 405, 775)}, file={'qq': 'templates/qq/btn/btn_claim_yellow.png', 'wechat': 'templates/qq/btn/btn_claim_yellow.png'}, name='btn_claim_yellow')
BTN_CLICK_TO_CLOSE = Button(area={'qq': (207, 793, 331, 811), 'wechat': (207, 793, 331, 811)}, color={'qq': (148, 141, 129), 'wechat': (148, 141, 129)}, button={'qq': (207, 793, 331, 811), 'wechat': (207, 793, 331, 811)}, file={'qq': 'templates/qq/btn/btn_click_to_close.png', 'wechat': 'templates/qq/btn/btn_click_to_close.png'}, name='btn_click_to_close')
BTN_CLOSE = Button(area={'qq': (493, 54, 527, 88), 'wechat': (493, 54, 527, 88)}, color={'qq': (236, 191, 165), 'wechat': (236, 191, 165)}, button={'qq': (493, 54, 527, 88), 'wechat': (493, 54, 527, 88)}, file={'qq': 'templates/qq/btn/btn_close.png', 'wechat': 'templates/qq/btn/btn_close.png'}, name='btn_close')  # 关闭
BTN_COME_AGAIN = Button(area={'qq': (223, 590, 316, 613), 'wechat': (223, 590, 316, 613)}, color={'qq': (187, 199, 98), 'wechat': (187, 199, 98)}, button={'qq': (223, 590, 316, 613), 'wechat': (223, 590, 316, 613)}, file={'qq': 'templates/qq/btn/btn_come_again.png', 'wechat': 'templates/qq/btn/btn_come_again.png'}, name='btn_come_again')
BTN_CONFIRM = Button(area={'qq': (349, 871, 403, 896), 'wechat': (349, 871, 403, 896)}, color={'qq': (182, 197, 86), 'wechat': (182, 197, 86)}, button={'qq': (349, 871, 403, 896), 'wechat': (349, 871, 403, 896)}, file={'qq': 'templates/qq/btn/btn_confirm.png', 'wechat': 'templates/qq/btn/btn_confirm.png'}, name='btn_confirm')  # 确认
BTN_CROP_MATURITY_TIME_SUFFIX = Button(area={'qq': (316, 475, 359, 489), 'wechat': (316, 475, 359, 489)}, color={'qq': (192, 157, 132), 'wechat': (192, 157, 132)}, button={'qq': (316, 475, 359, 489), 'wechat': (316, 475, 359, 489)}, file={'qq': 'templates/qq/btn/btn_crop_maturity_time_suffix.png', 'wechat': 'templates/qq/btn/btn_crop_maturity_time_suffix.png'}, name='btn_crop_maturity_time_suffix')
BTN_CROP_REMOVAL = Button(area={'qq': (469, 459, 495, 486), 'wechat': (469, 459, 495, 486)}, color={'qq': (220, 211, 191), 'wechat': (220, 211, 191)}, button={'qq': (469, 459, 495, 486), 'wechat': (469, 459, 495, 486)}, file={'qq': 'templates/qq/btn/btn_crop_removal.png', 'wechat': 'templates/qq/btn/btn_crop_removal.png'}, name='btn_crop_removal')
BTN_DIRECT_CLAIM = Button(area={'qq': (327, 733, 424, 759), 'wechat': (327, 733, 424, 759)}, color={'qq': (196, 204, 122), 'wechat': (196, 204, 122)}, button={'qq': (327, 733, 424, 759), 'wechat': (327, 733, 424, 759)}, file={'qq': 'templates/qq/btn/btn_direct_claim.png', 'wechat': 'templates/qq/btn/btn_direct_claim.png'}, name='btn_direct_claim')  # 领取
BTN_EXPAND = Button(area={'qq': (323, 558, 356, 591), 'wechat': (323, 558, 356, 591)}, color={'qq': (184, 153, 69), 'wechat': (184, 153, 69)}, button={'qq': (323, 558, 356, 591), 'wechat': (323, 558, 356, 591)}, file={'qq': 'templates/qq/btn/btn_expand.png', 'wechat': 'templates/qq/btn/btn_expand.png'}, name='btn_expand')  # 扩建
BTN_EXPAND_BRAND = Button(area={'qq': (213, 613, 237, 629), 'wechat': (213, 613, 237, 629)}, color={'qq': (164, 155, 65), 'wechat': (164, 155, 65)}, button={'qq': (213, 613, 237, 629), 'wechat': (213, 613, 237, 629)}, file={'qq': 'templates/qq/btn/btn_expand_brand.png', 'wechat': 'templates/qq/btn/btn_expand_brand.png'}, name='btn_expand_brand')
BTN_EXPAND_CHECK = Button(area={'qq': (219, 311, 314, 335), 'wechat': (219, 311, 314, 335)}, color={'qq': (229, 191, 172), 'wechat': (229, 191, 172)}, button={'qq': (219, 311, 314, 335), 'wechat': (219, 311, 314, 335)}, file={'qq': 'templates/qq/btn/btn_expand_check.png', 'wechat': 'templates/qq/btn/btn_expand_check.png'}, name='btn_expand_check')
BTN_EXPAND_CONFIRM = Button(area={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, color={'qq': (190, 201, 105), 'wechat': (190, 201, 105)}, button={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, file={'qq': 'templates/qq/btn/btn_expand_confirm.png', 'wechat': 'templates/qq/btn/btn_expand_confirm.png'}, name='btn_expand_confirm')
BTN_EXPAND_DIRECT_CONFIRM = Button(area={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, color={'qq': (190, 201, 105), 'wechat': (190, 201, 105)}, button={'qq': (245, 570, 295, 595), 'wechat': (245, 570, 295, 595)}, file={'qq': 'templates/qq/btn/btn_expand_direct_confirm.png', 'wechat': 'templates/qq/btn/btn_expand_direct_confirm.png'}, name='btn_expand_direct_confirm')
BTN_FARMING = Button(area={'qq': (249, 689, 279, 719), 'wechat': (249, 689, 279, 719)}, color={'qq': (153, 130, 100), 'wechat': (153, 130, 100)}, button={'qq': (249, 689, 279, 719), 'wechat': (249, 689, 279, 719)}, file={'qq': 'templates/qq/btn/btn_farming.png', 'wechat': 'templates/qq/btn/btn_farming.png'}, name='btn_farming')  # 一键务农
BTN_FERTILIZER_USE_CONFIRM = Button(area={'qq': (242, 609, 300, 638), 'wechat': (242, 609, 300, 638)}, color={'qq': (180, 196, 77), 'wechat': (180, 196, 77)}, button={'qq': (242, 609, 300, 638), 'wechat': (242, 609, 300, 638)}, file={'qq': 'templates/qq/btn/btn_fertilizer_use_confirm.png', 'wechat': 'templates/qq/btn/btn_fertilizer_use_confirm.png'}, name='btn_fertilizer_use_confirm')
BTN_FRIEND_AGREED = Button(area={'qq': (316, 687, 416, 713), 'wechat': (316, 687, 416, 713)}, color={'qq': (190, 200, 110), 'wechat': (190, 200, 110)}, button={'qq': (316, 687, 416, 713), 'wechat': (316, 687, 416, 713)}, file={'qq': 'templates/qq/btn/btn_friend_agreed.png', 'wechat': 'templates/qq/btn/btn_friend_agreed.png'}, name='btn_friend_agreed')
BTN_FRIEND_APPLY = Button(area={'qq': (220, 196, 318, 221), 'wechat': (220, 196, 318, 221)}, color={'qq': (226, 190, 167), 'wechat': (226, 190, 167)}, button={'qq': (220, 196, 318, 221), 'wechat': (220, 196, 318, 221)}, file={'qq': 'templates/qq/btn/btn_friend_apply.png', 'wechat': 'templates/qq/btn/btn_friend_apply.png'}, name='btn_friend_apply')
BTN_FRIEND_RIGHT_FRAME = Button(area={'qq': (141, 846, 153, 913), 'wechat': (141, 846, 153, 913)}, color={'qq': (198, 229, 133), 'wechat': (198, 229, 133)}, button={'qq': (141, 846, 153, 913), 'wechat': (141, 846, 153, 913)}, file={'qq': 'templates/qq/btn/btn_friend_right_frame.png', 'wechat': 'templates/qq/btn/btn_friend_right_frame.png'}, name='btn_friend_right_frame')
BTN_GRASS = Button(area={'qq': (247, 578, 282, 601), 'wechat': (247, 578, 282, 601)}, color={'qq': (116, 171, 63), 'wechat': (116, 171, 63)}, button={'qq': (247, 578, 282, 601), 'wechat': (247, 578, 282, 601)}, file={'qq': 'templates/qq/btn/btn_grass.png', 'wechat': 'templates/qq/btn/btn_grass.png'}, name='btn_grass')
BTN_GRASS_END = Button(area={'qq': (232, 545, 270, 571), 'wechat': (232, 545, 270, 571)}, color={'qq': (147, 145, 136), 'wechat': (147, 145, 136)}, button={'qq': (232, 545, 270, 571), 'wechat': (232, 545, 270, 571)}, file={'qq': 'templates/qq/btn/btn_grass_end.png', 'wechat': 'templates/qq/btn/btn_grass_end.png'}, name='btn_grass_end')
BTN_HARVEST = Button(area={'qq': (246, 688, 287, 720), 'wechat': (246, 688, 287, 720)}, color={'qq': (221, 169, 139), 'wechat': (221, 169, 139)}, button={'qq': (246, 688, 287, 720), 'wechat': (246, 688, 287, 720)}, file={'qq': 'templates/qq/btn/btn_harvest.png', 'wechat': 'templates/qq/btn/btn_harvest.png'}, name='btn_harvest')  # 一键收获
BTN_HARVEST_POP = Button(area={'qq': (431, 462, 483, 479), 'wechat': (431, 462, 483, 479)}, color={'qq': (141, 162, 164), 'wechat': (141, 162, 164)}, button={'qq': (431, 462, 483, 479), 'wechat': (431, 462, 483, 479)}, file={'qq': 'templates/qq/btn/btn_harvest_pop.png', 'wechat': 'templates/qq/btn/btn_harvest_pop.png'}, name='btn_harvest_pop')
BTN_HEFENG_100 = Button(area={'qq': (462, 270, 528, 286), 'wechat': (462, 270, 528, 286)}, color={'qq': (187, 159, 135), 'wechat': (187, 159, 135)}, button={'qq': (462, 270, 528, 286), 'wechat': (462, 270, 528, 286)}, file={'qq': 'templates/qq/event/btn_hefeng_100.png', 'wechat': 'templates/qq/event/btn_hefeng_100.png'}, name='btn_hefeng_100')
BTN_HEFENG_101 = Button(area={'qq': (221, 850, 322, 878), 'wechat': (221, 850, 322, 878)}, color={'qq': (183, 202, 170), 'wechat': (183, 202, 170)}, button={'qq': (221, 850, 322, 878), 'wechat': (221, 850, 322, 878)}, file={'qq': 'templates/qq/event/btn_hefeng_101.png', 'wechat': 'templates/qq/event/btn_hefeng_101.png'}, name='btn_hefeng_101')
BTN_HEFENG_102 = Button(area={'qq': (27, 701, 68, 726), 'wechat': (27, 701, 68, 726)}, color={'qq': (157, 131, 94), 'wechat': (157, 131, 94)}, button={'qq': (27, 701, 68, 726), 'wechat': (27, 701, 68, 726)}, file={'qq': 'templates/qq/event/btn_hefeng_102.png', 'wechat': 'templates/qq/event/btn_hefeng_102.png'}, name='btn_hefeng_102')
BTN_HEFENG_103 = Button(area={'qq': (355, 761, 445, 814), 'wechat': (355, 761, 445, 814)}, color={'qq': (238, 199, 143), 'wechat': (238, 199, 143)}, button={'qq': (355, 761, 445, 814), 'wechat': (355, 761, 445, 814)}, file={'qq': 'templates/qq/event/btn_hefeng_103.png', 'wechat': 'templates/qq/event/btn_hefeng_103.png'}, name='btn_hefeng_103')
BTN_HEFENG_104_S = Button(area={'qq': (349, 763, 445, 815), 'wechat': (349, 763, 445, 815)}, color={'qq': (212, 184, 125), 'wechat': (212, 184, 125)}, button={'qq': (349, 763, 445, 815), 'wechat': (349, 763, 445, 815)}, file={'qq': 'templates/qq/event/btn_hefeng_104_s.png', 'wechat': 'templates/qq/event/btn_hefeng_104_s.png'}, name='btn_hefeng_104_s')
BTN_HEFENG_105_S = Button(area={'qq': (359, 534, 407, 558), 'wechat': (359, 534, 407, 558)}, color={'qq': (191, 200, 113), 'wechat': (191, 200, 113)}, button={'qq': (359, 534, 407, 558), 'wechat': (359, 534, 407, 558)}, file={'qq': 'templates/qq/event/btn_hefeng_105_s.png', 'wechat': 'templates/qq/event/btn_hefeng_105_s.png'}, name='btn_hefeng_105_s')
BTN_HEFENG_106 = Button(area={'qq': (199, 890, 226, 923), 'wechat': (199, 890, 226, 923)}, color={'qq': (233, 161, 144), 'wechat': (233, 161, 144)}, button={'qq': (199, 890, 226, 923), 'wechat': (199, 890, 226, 923)}, file={'qq': 'templates/qq/event/btn_hefeng_106.png', 'wechat': 'templates/qq/event/btn_hefeng_106.png'}, name='btn_hefeng_106')
BTN_HEFENG_107 = Button(area={'qq': (224, 810, 319, 835), 'wechat': (224, 810, 319, 835)}, color={'qq': (150, 167, 133), 'wechat': (150, 167, 133)}, button={'qq': (224, 810, 319, 835), 'wechat': (224, 810, 319, 835)}, file={'qq': 'templates/qq/event/btn_hefeng_107.png', 'wechat': 'templates/qq/event/btn_hefeng_107.png'}, name='btn_hefeng_107')
BTN_HEFENG_108 = Button(area={'qq': (17, 62, 56, 95), 'wechat': (17, 62, 56, 95)}, color={'qq': (179, 197, 166), 'wechat': (179, 197, 166)}, button={'qq': (17, 62, 56, 95), 'wechat': (17, 62, 56, 95)}, file={'qq': 'templates/qq/event/btn_hefeng_108.png', 'wechat': 'templates/qq/event/btn_hefeng_108.png'}, name='btn_hefeng_108')
BTN_HOME = Button(area={'qq': (465, 697, 510, 729), 'wechat': (465, 697, 510, 729)}, color={'qq': (181, 126, 76), 'wechat': (181, 126, 76)}, button={'qq': (465, 697, 510, 729), 'wechat': (465, 697, 510, 729)}, file={'qq': 'templates/qq/btn/btn_home.png', 'wechat': 'templates/qq/btn/btn_home.png'}, name='btn_home')  # 回家
BTN_LAND_LEFT = Button(area={'qq': (152, 593, 167, 613), 'wechat': (152, 593, 167, 613)}, color={'qq': (191, 199, 88), 'wechat': (191, 199, 88)}, button={'qq': (152, 593, 167, 613), 'wechat': (152, 593, 167, 613)}, file={'qq': 'templates/qq/btn/btn_land_left.png', 'wechat': 'templates/qq/btn/btn_land_left.png'}, name='btn_land_left')
BTN_LAND_POP_EMPTY = Button(area={'qq': (194, 507, 222, 521), 'wechat': (194, 507, 222, 521)}, color={'qq': (208, 173, 147), 'wechat': (208, 173, 147)}, button={'qq': (194, 507, 222, 521), 'wechat': (194, 507, 222, 521)}, file={'qq': 'templates/qq/btn/btn_land_pop_empty.png', 'wechat': 'templates/qq/btn/btn_land_pop_empty.png'}, name='btn_land_pop_empty')
BTN_LAND_RIGHT = Button(area={'qq': (395, 545, 410, 565), 'wechat': (395, 545, 410, 565)}, color={'qq': (176, 196, 86), 'wechat': (176, 196, 86)}, button={'qq': (395, 545, 410, 565), 'wechat': (395, 545, 410, 565)}, file={'qq': 'templates/qq/btn/btn_land_right.png', 'wechat': 'templates/qq/btn/btn_land_right.png'}, name='btn_land_right')
BTN_LAND_RIGHT_2 = Button(area={'qq': (293, 530, 307, 549), 'wechat': (293, 530, 307, 549)}, color={'qq': (173, 198, 93), 'wechat': (173, 198, 93)}, button={'qq': (293, 530, 307, 549), 'wechat': (293, 530, 307, 549)}, file={'qq': 'templates/qq/btn/btn_land_right_2.png', 'wechat': 'templates/qq/btn/btn_land_right_2.png'}, name='btn_land_right_2')
BTN_LAND_UPGRADE_CHECK = Button(area={'qq': (223, 206, 317, 230), 'wechat': (223, 206, 317, 230)}, color={'qq': (225, 189, 166), 'wechat': (225, 189, 166)}, button={'qq': (223, 206, 317, 230), 'wechat': (223, 206, 317, 230)}, file={'qq': 'templates/qq/btn/btn_land_upgrade_check.png', 'wechat': 'templates/qq/btn/btn_land_upgrade_check.png'}, name='btn_land_upgrade_check')
BTN_LAND_UPGRADE_CONFIRM = Button(area={'qq': (245, 697, 295, 722), 'wechat': (245, 697, 295, 722)}, color={'qq': (190, 200, 106), 'wechat': (190, 200, 106)}, button={'qq': (245, 697, 295, 722), 'wechat': (245, 697, 295, 722)}, file={'qq': 'templates/qq/btn/btn_land_upgrade_confirm.png', 'wechat': 'templates/qq/btn/btn_land_upgrade_confirm.png'}, name='btn_land_upgrade_confirm')
BTN_LOGIN_AGAIN = Button(area={'qq': (325, 572, 423, 598), 'wechat': (325, 572, 423, 598)}, color={'qq': (195, 203, 121), 'wechat': (195, 203, 121)}, button={'qq': (325, 572, 423, 598), 'wechat': (325, 572, 423, 598)}, file={'qq': 'templates/qq/btn/btn_login_again.png', 'wechat': 'templates/qq/btn/btn_login_again.png'}, name='btn_login_again')
BTN_MALL_FREE = Button(area={'qq': (122, 539, 183, 569), 'wechat': (123, 536, 183, 568)}, color={'qq': (146, 167, 48), 'wechat': (140, 170, 45)}, button={'qq': (122, 539, 183, 569), 'wechat': (123, 536, 183, 568)}, file={'qq': 'templates/qq/btn/btn_mall_free.png', 'wechat': 'templates/wechat/btn/btn_mall_free.png'}, name='btn_mall_free')
BTN_MALL_FREE_DONE = Button(area={'qq': (121, 539, 183, 570), 'wechat': (123, 535, 183, 568)}, color={'qq': (208, 176, 139), 'wechat': (210, 182, 149)}, button={'qq': (121, 539, 183, 570), 'wechat': (123, 535, 183, 568)}, file={'qq': 'templates/qq/btn/btn_mall_free_done.png', 'wechat': 'templates/wechat/btn/btn_mall_free_done.png'}, name='btn_mall_free_done')
BTN_MATURE = Button(area={'qq': (261, 457, 278, 479), 'wechat': (261, 457, 278, 479)}, color={'qq': (201, 181, 78), 'wechat': (201, 181, 78)}, button={'qq': (261, 457, 278, 479), 'wechat': (261, 457, 278, 479)}, file={'qq': 'templates/qq/btn/btn_mature.png', 'wechat': 'templates/qq/btn/btn_mature.png'}, name='btn_mature')
BTN_MENU = Button(area={'qq': (0, 0, 26, 26), 'wechat': (0, 0, 26, 26)}, color={'qq': (249, 249, 249), 'wechat': (249, 249, 249)}, button={'qq': (0, 0, 26, 26), 'wechat': (0, 0, 26, 26)}, file={'qq': 'templates/qq/btn/btn_menu.png', 'wechat': 'templates/qq/btn/btn_menu.png'}, name='btn_menu')
BTN_MONTHLY_CARD = Button(area={'qq': (213, 893, 333, 922), 'wechat': (213, 893, 333, 922)}, color={'qq': (182, 139, 102), 'wechat': (182, 139, 102)}, button={'qq': (213, 893, 333, 922), 'wechat': (213, 893, 333, 922)}, file={'qq': 'templates/qq/btn/btn_monthly_card.png', 'wechat': 'templates/qq/btn/btn_monthly_card.png'}, name='btn_monthly_card')
BTN_MONTHLY_CARD_ACCEPT = Button(area={'qq': (246, 730, 298, 757), 'wechat': (246, 730, 298, 757)}, color={'qq': (187, 204, 104), 'wechat': (187, 204, 104)}, button={'qq': (246, 730, 298, 757), 'wechat': (246, 730, 298, 757)}, file={'qq': 'templates/qq/btn/btn_monthly_card_accept.png', 'wechat': 'templates/qq/btn/btn_monthly_card_accept.png'}, name='btn_monthly_card_accept')
BTN_MONTHLY_CARD_END = Button(area={'qq': (223, 731, 320, 755), 'wechat': (223, 731, 320, 755)}, color={'qq': (181, 200, 89), 'wechat': (181, 200, 89)}, button={'qq': (223, 731, 320, 755), 'wechat': (223, 731, 320, 755)}, file={'qq': 'templates/qq/btn/btn_monthly_card_end.png', 'wechat': 'templates/qq/btn/btn_monthly_card_end.png'}, name='btn_monthly_card_end')
BTN_MONTHLY_CARD_END_2 = Button(area={'qq': (237, 729, 307, 756), 'wechat': (237, 729, 307, 756)}, color={'qq': (212, 227, 125), 'wechat': (212, 227, 125)}, button={'qq': (237, 729, 307, 756), 'wechat': (237, 729, 307, 756)}, file={'qq': 'templates/qq/btn/btn_monthly_card_end_2.png', 'wechat': 'templates/qq/btn/btn_monthly_card_end_2.png'}, name='btn_monthly_card_end_2')
BTN_ONECLICK_OPEN = Button(area={'qq': (326, 805, 419, 829), 'wechat': (326, 805, 419, 829)}, color={'qq': (183, 197, 88), 'wechat': (183, 197, 88)}, button={'qq': (326, 805, 419, 829), 'wechat': (326, 805, 419, 829)}, file={'qq': 'templates/qq/btn/btn_oneclick_open.png', 'wechat': 'templates/qq/btn/btn_oneclick_open.png'}, name='btn_oneclick_open')
BTN_ORDINARY_FERTILIZER = Button(area={'qq': (115, 610, 159, 642), 'wechat': (115, 610, 159, 642)}, color={'qq': (200, 134, 76), 'wechat': (200, 134, 76)}, button={'qq': (115, 610, 159, 642), 'wechat': (115, 610, 159, 642)}, file={'qq': 'templates/qq/btn/btn_ordinary_fertilizer.png', 'wechat': 'templates/qq/btn/btn_ordinary_fertilizer.png'}, name='btn_ordinary_fertilizer')
BTN_ORGANIC_FERTILIZER = Button(area={'qq': (202, 613, 248, 640), 'wechat': (202, 613, 248, 640)}, color={'qq': (175, 139, 35), 'wechat': (175, 139, 35)}, button={'qq': (202, 613, 248, 640), 'wechat': (202, 613, 248, 640)}, file={'qq': 'templates/qq/btn/btn_organic_fertilizer.png', 'wechat': 'templates/qq/btn/btn_organic_fertilizer.png'}, name='btn_organic_fertilizer')
BTN_PLANTING = Button(area={'qq': (233, 866, 307, 893), 'wechat': (233, 866, 307, 893)}, color={'qq': (190, 201, 107), 'wechat': (190, 201, 107)}, button={'qq': (233, 866, 307, 893), 'wechat': (233, 866, 307, 893)}, file={'qq': 'templates/qq/btn/btn_planting.png', 'wechat': 'templates/qq/btn/btn_planting.png'}, name='btn_planting')
BTN_QQSVIP = Button(area={'qq': (112, 148, 133, 179), 'wechat': (112, 148, 133, 179)}, color={'qq': (133, 103, 69), 'wechat': (133, 103, 69)}, button={'qq': (112, 148, 133, 179), 'wechat': (112, 148, 133, 179)}, file={'qq': 'templates/qq/btn/btn_qqsvip.png', 'wechat': 'templates/qq/btn/btn_qqsvip.png'}, name='btn_qqsvip')
BTN_QQSVIP_CHECK = Button(area={'qq': (194, 265, 289, 283), 'wechat': (194, 265, 289, 283)}, color={'qq': (225, 188, 165), 'wechat': (225, 188, 165)}, button={'qq': (194, 265, 289, 283), 'wechat': (194, 265, 289, 283)}, file={'qq': 'templates/qq/btn/btn_qqsvip_check.png', 'wechat': 'templates/qq/btn/btn_qqsvip_check.png'}, name='btn_qqsvip_check')
BTN_SHARE_GREEN = Button(area={'qq': (356, 753, 406, 778), 'wechat': (356, 753, 406, 778)}, color={'qq': (178, 195, 76), 'wechat': (178, 195, 76)}, button={'qq': (356, 753, 406, 778), 'wechat': (356, 753, 406, 778)}, file={'qq': 'templates/qq/btn/btn_share_green.png', 'wechat': 'templates/qq/btn/btn_share_green.png'}, name='btn_share_green')
BTN_SHARE_RED_POINT = Button(area={'qq': (445, 731, 462, 748), 'wechat': (445, 731, 462, 748)}, color={'qq': (232, 112, 92), 'wechat': (232, 112, 92)}, button={'qq': (445, 731, 462, 748), 'wechat': (445, 731, 462, 748)}, file={'qq': 'templates/qq/btn/btn_share_red_point.png', 'wechat': 'templates/qq/btn/btn_share_red_point.png'}, name='btn_share_red_point')
BTN_SHARE_YELLOW = Button(area={'qq': (139, 733, 190, 760), 'wechat': (139, 733, 190, 760)}, color={'qq': (223, 185, 102), 'wechat': (223, 185, 102)}, button={'qq': (139, 733, 190, 760), 'wechat': (139, 733, 190, 760)}, file={'qq': 'templates/qq/btn/btn_share_yellow.png', 'wechat': 'templates/qq/btn/btn_share_yellow.png'}, name='btn_share_yellow')
BTN_SHOP_BUY_CHECK = Button(area={'qq': (247, 268, 293, 291), 'wechat': (247, 268, 293, 292)}, color={'qq': (228, 190, 171), 'wechat': (233, 200, 183)}, button={'qq': (247, 268, 293, 291), 'wechat': (247, 268, 293, 292)}, file={'qq': 'templates/qq/btn/btn_shop_buy_check.png', 'wechat': 'templates/wechat/btn/btn_shop_buy_check.png'}, name='btn_shop_buy_check')
BTN_SHOP_BUY_CONFIRM = Button(area={'qq': (246, 622, 295, 648), 'wechat': (246, 622, 295, 648)}, color={'qq': (189, 200, 104), 'wechat': (189, 200, 104)}, button={'qq': (246, 622, 295, 648), 'wechat': (246, 622, 295, 648)}, file={'qq': 'templates/qq/btn/btn_shop_buy_confirm.png', 'wechat': 'templates/qq/btn/btn_shop_buy_confirm.png'}, name='btn_shop_buy_confirm')
BTN_SPECIAL_WAREHOUSE = Button(area={'qq': (162, 128, 253, 153), 'wechat': (162, 128, 253, 153)}, color={'qq': (205, 158, 127), 'wechat': (205, 158, 127)}, button={'qq': (162, 128, 253, 153), 'wechat': (162, 128, 253, 153)}, file={'qq': 'templates/qq/btn/btn_special_warehouse.png', 'wechat': 'templates/qq/btn/btn_special_warehouse.png'}, name='btn_special_warehouse')
BTN_STEAL = Button(area={'qq': (248, 692, 284, 720), 'wechat': (248, 692, 284, 720)}, color={'qq': (187, 147, 123), 'wechat': (187, 147, 123)}, button={'qq': (248, 692, 284, 720), 'wechat': (248, 692, 284, 720)}, file={'qq': 'templates/qq/btn/btn_steal.png', 'wechat': 'templates/qq/btn/btn_steal.png'}, name='btn_steal')
BTN_STEAL_SIGN = Button(area={'qq': (124, 799, 154, 919), 'wechat': (124, 799, 154, 919)}, color={'qq': (224, 222, 164), 'wechat': (224, 222, 164)}, button={'qq': (124, 799, 154, 919), 'wechat': (124, 799, 154, 919)}, file={'qq': 'templates/qq/btn/btn_steal_sign.png', 'wechat': 'templates/qq/btn/btn_steal_sign.png'}, name='btn_steal_sign')
BTN_STEAL_SINGLE = Button(area={'qq': (332, 493, 356, 518), 'wechat': (332, 493, 356, 518)}, color={'qq': (198, 185, 114), 'wechat': (198, 185, 114)}, button={'qq': (332, 493, 356, 518), 'wechat': (332, 493, 356, 518)}, file={'qq': 'templates/qq/btn/btn_steal_single.png', 'wechat': 'templates/qq/btn/btn_steal_single.png'}, name='btn_steal_single')
BTN_STEAL_SINGLE_2 = Button(area={'qq': (267, 408, 292, 432), 'wechat': (267, 408, 292, 432)}, color={'qq': (211, 202, 115), 'wechat': (211, 202, 115)}, button={'qq': (267, 408, 292, 432), 'wechat': (267, 408, 292, 432)}, file={'qq': 'templates/qq/btn/btn_steal_single_2.png', 'wechat': 'templates/qq/btn/btn_steal_single_2.png'}, name='btn_steal_single_2')
BTN_VISIT_FIRST = Button(area={'qq': (443, 295, 480, 314), 'wechat': (443, 295, 480, 314)}, color={'qq': (183, 195, 99), 'wechat': (183, 195, 99)}, button={'qq': (443, 295, 480, 314), 'wechat': (443, 295, 480, 314)}, file={'qq': 'templates/qq/btn/btn_visit_first.png', 'wechat': 'templates/qq/btn/btn_visit_first.png'}, name='btn_visit_first')
BTN_WAREHOUSE_SEED_20_EMPTY = Button(area={'qq': (424, 522, 508, 615), 'wechat': (424, 522, 508, 615)}, color={'qq': (239, 214, 169), 'wechat': (239, 214, 169)}, button={'qq': (424, 522, 508, 615), 'wechat': (424, 522, 508, 615)}, file={'qq': 'templates/qq/btn/btn_warehouse_seed_20_empty.png', 'wechat': 'templates/qq/btn/btn_warehouse_seed_20_empty.png'}, name='btn_warehouse_seed_20_empty')
BTN_WITHERED = Button(area={'qq': (336, 475, 348, 490), 'wechat': (336, 475, 348, 490)}, color={'qq': (107, 96, 51), 'wechat': (107, 96, 51)}, button={'qq': (336, 475, 348, 490), 'wechat': (336, 475, 348, 490)}, file={'qq': 'templates/qq/btn/btn_withered.png', 'wechat': 'templates/qq/btn/btn_withered.png'}, name='btn_withered')
FRIEND_CHECK = Button(area={'qq': (241, 69, 299, 98), 'wechat': (241, 69, 299, 98)}, color={'qq': (225, 186, 159), 'wechat': (225, 186, 159)}, button={'qq': (241, 69, 299, 98), 'wechat': (241, 69, 299, 98)}, file={'qq': 'templates/qq/ui/friend_check.png', 'wechat': 'templates/qq/ui/friend_check.png'}, name='friend_check')
ICON_FARMING_IN_FRIEND_LIST = Button(area={'qq': (0, 0, 22, 22), 'wechat': (0, 0, 22, 22)}, color={'qq': (181, 167, 137), 'wechat': (181, 167, 137)}, button={'qq': (0, 0, 22, 22), 'wechat': (0, 0, 22, 22)}, file={'qq': 'templates/qq/icon/icon_farming_in_friend_list.png', 'wechat': 'templates/qq/icon/icon_farming_in_friend_list.png'}, name='icon_farming_in_friend_list')
ICON_GUARD_DOG = Button(area={'qq': (0, 0, 15, 15), 'wechat': (0, 0, 15, 15)}, color={'qq': (219, 198, 172), 'wechat': (219, 198, 172)}, button={'qq': (0, 0, 15, 15), 'wechat': (0, 0, 15, 15)}, file={'qq': 'templates/qq/icon/icon_guard_dog.gif', 'wechat': 'templates/qq/icon/icon_guard_dog.gif'}, name='icon_guard_dog')
ICON_ITEM_LOCKED = Button(area={'qq': (0, 0, 15, 16), 'wechat': (0, 0, 15, 16)}, color={'qq': (240, 196, 133), 'wechat': (240, 196, 133)}, button={'qq': (0, 0, 15, 16), 'wechat': (0, 0, 15, 16)}, file={'qq': 'templates/qq/icon/icon_item_locked.png', 'wechat': 'templates/qq/icon/icon_item_locked.png'}, name='icon_item_locked')
ICON_LAND_AMETHYST = Button(area={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, color={'qq': (209, 168, 232), 'wechat': (209, 168, 232)}, button={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, file={'qq': 'templates/qq/land/icon_land_amethyst.png', 'wechat': 'templates/qq/land/icon_land_amethyst.png'}, name='icon_land_amethyst')
ICON_LAND_BLACK = Button(area={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, color={'qq': (92, 67, 42), 'wechat': (92, 67, 42)}, button={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, file={'qq': 'templates/qq/land/icon_land_black.png', 'wechat': 'templates/qq/land/icon_land_black.png'}, name='icon_land_black')
ICON_LAND_GOLD = Button(area={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, color={'qq': (249, 203, 50), 'wechat': (249, 203, 50)}, button={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, file={'qq': 'templates/qq/land/icon_land_gold.png', 'wechat': 'templates/qq/land/icon_land_gold.png'}, name='icon_land_gold')
ICON_LAND_GOLD_2 = Button(area={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, color={'qq': (249, 204, 51), 'wechat': (249, 204, 51)}, button={'qq': (0, 0, 19, 17), 'wechat': (0, 0, 19, 17)}, file={'qq': 'templates/qq/land/icon_land_gold_2.png', 'wechat': 'templates/qq/land/icon_land_gold_2.png'}, name='icon_land_gold_2')
ICON_LAND_RED = Button(area={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, color={'qq': (223, 87, 55), 'wechat': (223, 87, 55)}, button={'qq': (0, 0, 23, 15), 'wechat': (0, 0, 23, 15)}, file={'qq': 'templates/qq/land/icon_land_red.png', 'wechat': 'templates/qq/land/icon_land_red.png'}, name='icon_land_red')
ICON_LAND_STAND = Button(area={'qq': (0, 0, 19, 16), 'wechat': (0, 0, 19, 16)}, color={'qq': (178, 131, 74), 'wechat': (178, 131, 74)}, button={'qq': (0, 0, 19, 16), 'wechat': (0, 0, 19, 16)}, file={'qq': 'templates/qq/land/icon_land_stand.png', 'wechat': 'templates/qq/land/icon_land_stand.png'}, name='icon_land_stand')
ICON_LAND_UPGRADE = Button(area={'qq': (0, 0, 14, 18), 'wechat': (0, 0, 14, 18)}, color={'qq': (193, 235, 96), 'wechat': (193, 235, 96)}, button={'qq': (0, 0, 14, 18), 'wechat': (0, 0, 14, 18)}, file={'qq': 'templates/qq/icon/icon_land_upgrade.gif', 'wechat': 'templates/qq/icon/icon_land_upgrade.gif'}, name='icon_land_upgrade')
ICON_NUM_0 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (147, 136, 119), 'wechat': (147, 136, 119)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_0.png', 'wechat': 'templates/qq/icon/icon_num_0.png'}, name='icon_num_0')
ICON_NUM_1 = Button(area={'qq': (0, 0, 5, 12), 'wechat': (0, 0, 5, 12)}, color={'qq': (161, 150, 131), 'wechat': (161, 150, 131)}, button={'qq': (0, 0, 5, 12), 'wechat': (0, 0, 5, 12)}, file={'qq': 'templates/qq/icon/icon_num_1.png', 'wechat': 'templates/qq/icon/icon_num_1.png'}, name='icon_num_1')
ICON_NUM_2 = Button(area={'qq': (0, 0, 7, 17), 'wechat': (0, 0, 7, 17)}, color={'qq': (175, 164, 143), 'wechat': (175, 164, 143)}, button={'qq': (0, 0, 7, 17), 'wechat': (0, 0, 7, 17)}, file={'qq': 'templates/qq/icon/icon_num_2.png', 'wechat': 'templates/qq/icon/icon_num_2.png'}, name='icon_num_2')
ICON_NUM_3 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (159, 148, 130), 'wechat': (159, 148, 130)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_3.png', 'wechat': 'templates/qq/icon/icon_num_3.png'}, name='icon_num_3')
ICON_NUM_4 = Button(area={'qq': (0, 0, 9, 11), 'wechat': (0, 0, 9, 11)}, color={'qq': (164, 153, 134), 'wechat': (164, 153, 134)}, button={'qq': (0, 0, 9, 11), 'wechat': (0, 0, 9, 11)}, file={'qq': 'templates/qq/icon/icon_num_4.png', 'wechat': 'templates/qq/icon/icon_num_4.png'}, name='icon_num_4')
ICON_NUM_5 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (146, 136, 118), 'wechat': (146, 136, 118)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_5.png', 'wechat': 'templates/qq/icon/icon_num_5.png'}, name='icon_num_5')
ICON_NUM_6 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (139, 129, 112), 'wechat': (139, 129, 112)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_6.png', 'wechat': 'templates/qq/icon/icon_num_6.png'}, name='icon_num_6')
ICON_NUM_7 = Button(area={'qq': (0, 0, 8, 12), 'wechat': (0, 0, 8, 12)}, color={'qq': (183, 172, 151), 'wechat': (183, 172, 151)}, button={'qq': (0, 0, 8, 12), 'wechat': (0, 0, 8, 12)}, file={'qq': 'templates/qq/icon/icon_num_7.png', 'wechat': 'templates/qq/icon/icon_num_7.png'}, name='icon_num_7')
ICON_NUM_8 = Button(area={'qq': (0, 0, 7, 12), 'wechat': (0, 0, 7, 12)}, color={'qq': (137, 127, 111), 'wechat': (137, 127, 111)}, button={'qq': (0, 0, 7, 12), 'wechat': (0, 0, 7, 12)}, file={'qq': 'templates/qq/icon/icon_num_8.png', 'wechat': 'templates/qq/icon/icon_num_8.png'}, name='icon_num_8')
ICON_NUM_9 = Button(area={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, color={'qq': (139, 129, 112), 'wechat': (139, 129, 112)}, button={'qq': (0, 0, 8, 11), 'wechat': (0, 0, 8, 11)}, file={'qq': 'templates/qq/icon/icon_num_9.png', 'wechat': 'templates/qq/icon/icon_num_9.png'}, name='icon_num_9')
ICON_NUM_LEFT = Button(area={'qq': (0, 0, 8, 26), 'wechat': (0, 0, 8, 26)}, color={'qq': (191, 171, 95), 'wechat': (191, 171, 95)}, button={'qq': (0, 0, 8, 26), 'wechat': (0, 0, 8, 26)}, file={'qq': 'templates/qq/icon/icon_num_left.png', 'wechat': 'templates/qq/icon/icon_num_left.png'}, name='icon_num_left')
ICON_SEED_LOCKED = Button(area={'qq': (0, 0, 22, 21), 'wechat': (0, 0, 22, 21)}, color={'qq': (213, 196, 171), 'wechat': (213, 196, 171)}, button={'qq': (0, 0, 22, 21), 'wechat': (0, 0, 22, 21)}, file={'qq': 'templates/qq/icon/icon_seed_locked.png', 'wechat': 'templates/qq/icon/icon_seed_locked.png'}, name='icon_seed_locked')
ICON_STEAL_IN_FRIEND_DETAIL = Button(area={'qq': (0, 0, 13, 20), 'wechat': (0, 0, 13, 20)}, color={'qq': (176, 142, 113), 'wechat': (176, 142, 113)}, button={'qq': (0, 0, 13, 20), 'wechat': (0, 0, 13, 20)}, file={'qq': 'templates/qq/icon/icon_steal_in_friend_detail.png', 'wechat': 'templates/qq/icon/icon_steal_in_friend_detail.png'}, name='icon_steal_in_friend_detail')
ICON_STEAL_IN_FRIEND_LIST = Button(area={'qq': (0, 0, 30, 28), 'wechat': (0, 0, 30, 28)}, color={'qq': (212, 188, 169), 'wechat': (212, 188, 169)}, button={'qq': (0, 0, 30, 28), 'wechat': (0, 0, 30, 28)}, file={'qq': 'templates/qq/icon/icon_steal_in_friend_list.png', 'wechat': 'templates/qq/icon/icon_steal_in_friend_list.png'}, name='icon_steal_in_friend_list')
MAIL_CHECK = Button(area={'qq': (245, 74, 295, 100), 'wechat': (244, 73, 297, 100)}, color={'qq': (231, 198, 172), 'wechat': (236, 206, 181)}, button={'qq': (245, 74, 295, 100), 'wechat': (244, 73, 297, 100)}, file={'qq': 'templates/qq/ui/mail_check.png', 'wechat': 'templates/wechat/ui/mail_check.png'}, name='mail_check')
MAIN_GOTO_FRIEND = Button(area={'qq': (465, 905, 505, 925), 'wechat': (465, 905, 505, 925)}, color={'qq': (202, 154, 121), 'wechat': (202, 154, 121)}, button={'qq': (465, 905, 505, 925), 'wechat': (465, 905, 505, 925)}, file={'qq': 'templates/qq/ui/main_goto_friend.png', 'wechat': 'templates/qq/ui/main_goto_friend.png'}, name='main_goto_friend')
MAIN_GOTO_MALL = Button(area={'qq': (474, 164, 505, 189), 'wechat': (474, 164, 505, 189)}, color={'qq': (184, 182, 97), 'wechat': (184, 182, 97)}, button={'qq': (474, 164, 505, 189), 'wechat': (474, 164, 505, 189)}, file={'qq': 'templates/qq/ui/main_goto_mall.png', 'wechat': 'templates/qq/ui/main_goto_mall.png'}, name='main_goto_mall')
MAIN_GOTO_MENU = Button(area={'qq': (32, 300, 49, 319), 'wechat': (32, 300, 49, 319)}, color={'qq': (229, 191, 127), 'wechat': (229, 191, 127)}, button={'qq': (32, 300, 49, 319), 'wechat': (32, 300, 49, 319)}, file={'qq': 'templates/qq/ui/main_goto_menu.png', 'wechat': 'templates/qq/ui/main_goto_menu.png'}, name='main_goto_menu')
MAIN_GOTO_PET = Button(area={'qq': (221, 861, 270, 895), 'wechat': (221, 861, 270, 895)}, color={'qq': (197, 174, 169), 'wechat': (197, 174, 169)}, button={'qq': (221, 861, 270, 895), 'wechat': (221, 861, 270, 895)}, file={'qq': 'templates/qq/ui/main_goto_pet.png', 'wechat': 'templates/qq/ui/main_goto_pet.png'}, name='main_goto_pet')
MAIN_GOTO_SHARE = Button(area={'qq': (34, 160, 59, 183), 'wechat': (34, 160, 59, 183)}, color={'qq': (205, 156, 99), 'wechat': (205, 156, 99)}, button={'qq': (34, 160, 59, 183), 'wechat': (34, 160, 59, 183)}, file={'qq': 'templates/qq/ui/main_goto_share.png', 'wechat': 'templates/qq/ui/main_goto_share.png'}, name='main_goto_share')
MAIN_GOTO_SHOP = Button(area={'qq': (114, 905, 153, 924), 'wechat': (114, 905, 153, 924)}, color={'qq': (209, 167, 136), 'wechat': (209, 167, 136)}, button={'qq': (114, 905, 153, 924), 'wechat': (114, 905, 153, 924)}, file={'qq': 'templates/qq/ui/main_goto_shop.png', 'wechat': 'templates/qq/ui/main_goto_shop.png'}, name='main_goto_shop')
MAIN_GOTO_SKIN = Button(area={'qq': (282, 897, 321, 918), 'wechat': (282, 897, 321, 918)}, color={'qq': (208, 165, 134), 'wechat': (208, 165, 134)}, button={'qq': (282, 897, 321, 918), 'wechat': (282, 897, 321, 918)}, file={'qq': 'templates/qq/ui/main_goto_skin.png', 'wechat': 'templates/qq/ui/main_goto_skin.png'}, name='main_goto_skin')
MAIN_GOTO_TASK = Button(area={'qq': (34, 782, 64, 812), 'wechat': (34, 782, 64, 812)}, color={'qq': (222, 190, 149), 'wechat': (222, 190, 149)}, button={'qq': (34, 782, 64, 812), 'wechat': (34, 782, 64, 812)}, file={'qq': 'templates/qq/ui/main_goto_task.png', 'wechat': 'templates/qq/ui/main_goto_task.png'}, name='main_goto_task')
MAIN_GOTO_WAREHOUSE = Button(area={'qq': (31, 905, 70, 924), 'wechat': (31, 905, 70, 924)}, color={'qq': (205, 159, 127), 'wechat': (205, 159, 127)}, button={'qq': (31, 905, 70, 924), 'wechat': (31, 905, 70, 924)}, file={'qq': 'templates/qq/ui/main_goto_warehouse.png', 'wechat': 'templates/qq/ui/main_goto_warehouse.png'}, name='main_goto_warehouse')
MAIN_GOTO_WIKI = Button(area={'qq': (281, 904, 320, 923), 'wechat': (281, 904, 320, 923)}, color={'qq': (216, 180, 151), 'wechat': (216, 180, 151)}, button={'qq': (281, 904, 320, 923), 'wechat': (281, 904, 320, 923)}, file={'qq': 'templates/qq/ui/main_goto_wiki.png', 'wechat': 'templates/qq/ui/main_goto_wiki.png'}, name='main_goto_wiki')
MALL_CHECK = Button(area={'qq': (117, 83, 174, 112), 'wechat': (117, 83, 174, 112)}, color={'qq': (193, 156, 137), 'wechat': (193, 156, 137)}, button={'qq': (117, 83, 174, 112), 'wechat': (117, 83, 174, 112)}, file={'qq': 'templates/qq/ui/mall_check.png', 'wechat': 'templates/qq/ui/mall_check.png'}, name='mall_check')
MALL_CHECK_2 = Button(area={'qq': (111, 78, 179, 113), 'wechat': (111, 78, 179, 113)}, color={'qq': (223, 189, 173), 'wechat': (223, 189, 173)}, button={'qq': (111, 78, 179, 113), 'wechat': (111, 78, 179, 113)}, file={'qq': 'templates/qq/ui/mall_check_2.png', 'wechat': 'templates/qq/ui/mall_check_2.png'}, name='mall_check_2')
MALL_GOTO_MAIN = Button(area={'qq': (44, 93, 82, 122), 'wechat': (44, 93, 82, 122)}, color={'qq': (230, 187, 117), 'wechat': (230, 187, 117)}, button={'qq': (44, 93, 82, 122), 'wechat': (44, 93, 82, 122)}, file={'qq': 'templates/qq/ui/mall_goto_main.png', 'wechat': 'templates/qq/ui/mall_goto_main.png'}, name='mall_goto_main')
MENU_CHECK = Button(area={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, color={'qq': (244, 210, 136), 'wechat': (244, 210, 136)}, button={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, file={'qq': 'templates/qq/ui/menu_check.png', 'wechat': 'templates/qq/ui/menu_check.png'}, name='menu_check')
MENU_GOTO_MAIL = Button(area={'qq': (30, 486, 44, 505), 'wechat': (30, 486, 44, 505)}, color={'qq': (237, 206, 137), 'wechat': (237, 206, 137)}, button={'qq': (30, 486, 44, 505), 'wechat': (30, 486, 44, 505)}, file={'qq': 'templates/qq/ui/menu_goto_mail.png', 'wechat': 'templates/qq/ui/menu_goto_mail.png'}, name='menu_goto_mail')  # 邮件
MENU_GOTO_MAIN = Button(area={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, color={'qq': (244, 210, 136), 'wechat': (244, 210, 136)}, button={'qq': (31, 300, 51, 319), 'wechat': (31, 300, 51, 319)}, file={'qq': 'templates/qq/ui/menu_goto_main.png', 'wechat': 'templates/qq/ui/menu_goto_main.png'}, name='menu_goto_main')
PET_CHECK = Button(area={'qq': (241, 77, 294, 105), 'wechat': (241, 77, 294, 105)}, color={'qq': (232, 199, 181), 'wechat': (232, 199, 181)}, button={'qq': (241, 77, 294, 105), 'wechat': (241, 77, 294, 105)}, file={'qq': 'templates/qq/ui/pet_check.png', 'wechat': 'templates/qq/ui/pet_check.png'}, name='pet_check')
SEED_BTN_COLORED_GLAZE_LOTUS = Button(area={'qq': (171, 606, 209, 629), 'wechat': (171, 606, 209, 629)}, color={'qq': (222, 208, 238), 'wechat': (222, 208, 238)}, button={'qq': (171, 606, 209, 629), 'wechat': (171, 606, 209, 629)}, file={'qq': 'templates/qq/seedbtn/seed_btn_colored_glaze_lotus.png', 'wechat': 'templates/qq/seedbtn/seed_btn_colored_glaze_lotus.png'}, name='seed_btn_colored_glaze_lotus')
SEED_BTN_HAHA_PUMPKIN = Button(area={'qq': (84, 674, 113, 693), 'wechat': (84, 674, 113, 693)}, color={'qq': (233, 180, 119), 'wechat': (233, 180, 119)}, button={'qq': (84, 674, 113, 693), 'wechat': (84, 674, 113, 693)}, file={'qq': 'templates/qq/seedbtn/seed_btn_haha_pumpkin.png', 'wechat': 'templates/qq/seedbtn/seed_btn_haha_pumpkin.png'}, name='seed_btn_haha_pumpkin')
SEED_BTN_HEART_FRUIT = Button(area={'qq': (81, 613, 120, 637), 'wechat': (81, 613, 120, 637)}, color={'qq': (243, 176, 78), 'wechat': (243, 176, 78)}, button={'qq': (81, 613, 120, 637), 'wechat': (81, 613, 120, 637)}, file={'qq': 'templates/qq/seedbtn/seed_btn_heart_fruit.png', 'wechat': 'templates/qq/seedbtn/seed_btn_heart_fruit.png'}, name='seed_btn_heart_fruit')
SEED_BTN_MUGWORT = Button(area={'qq': (193, 651, 219, 671), 'wechat': (193, 651, 219, 671)}, color={'qq': (111, 165, 77), 'wechat': (111, 165, 77)}, button={'qq': (193, 651, 219, 671), 'wechat': (193, 651, 219, 671)}, file={'qq': 'templates/qq/seedbtn/seed_btn_mugwort.png', 'wechat': 'templates/qq/seedbtn/seed_btn_mugwort.png'}, name='seed_btn_mugwort')
SETTING_CHECK = Button(area={'qq': (31, 607, 53, 632), 'wechat': (31, 607, 53, 632)}, color={'qq': (227, 183, 122), 'wechat': (227, 183, 122)}, button={'qq': (31, 607, 53, 632), 'wechat': (31, 607, 53, 632)}, file={'qq': 'templates/qq/ui/setting_check.png', 'wechat': 'templates/qq/ui/setting_check.png'}, name='setting_check')
SHARE_CHECK = Button(area={'qq': (64, 142, 130, 175), 'wechat': (64, 142, 130, 175)}, color={'qq': (194, 160, 136), 'wechat': (194, 160, 136)}, button={'qq': (64, 142, 130, 175), 'wechat': (64, 142, 130, 175)}, file={'qq': 'templates/qq/ui/share_check.png', 'wechat': 'templates/qq/ui/share_check.png'}, name='share_check')
SHOP_CHECK = Button(area={'qq': (241, 85, 298, 113), 'wechat': (241, 85, 298, 113)}, color={'qq': (225, 191, 168), 'wechat': (225, 191, 168)}, button={'qq': (241, 85, 298, 113), 'wechat': (241, 85, 298, 113)}, file={'qq': 'templates/qq/ui/shop_check.png', 'wechat': 'templates/qq/ui/shop_check.png'}, name='shop_check')
SKIN_CHECK = Button(area={'qq': (246, 591, 303, 621), 'wechat': (246, 591, 303, 621)}, color={'qq': (221, 181, 157), 'wechat': (221, 181, 157)}, button={'qq': (246, 591, 303, 621), 'wechat': (246, 591, 303, 621)}, file={'qq': 'templates/qq/ui/skin_check.png', 'wechat': 'templates/qq/ui/skin_check.png'}, name='skin_check')
TASK_CHECK = Button(area={'qq': (242, 87, 298, 115), 'wechat': (242, 87, 298, 115)}, color={'qq': (224, 188, 165), 'wechat': (224, 188, 165)}, button={'qq': (242, 87, 298, 115), 'wechat': (242, 87, 298, 115)}, file={'qq': 'templates/qq/ui/task_check.png', 'wechat': 'templates/qq/ui/task_check.png'}, name='task_check')
WAREHOUSE_CHECK = Button(area={'qq': (242, 70, 298, 98), 'wechat': (242, 70, 298, 98)}, color={'qq': (226, 188, 168), 'wechat': (226, 188, 168)}, button={'qq': (242, 70, 298, 98), 'wechat': (242, 70, 298, 98)}, file={'qq': 'templates/qq/ui/warehouse_check.png', 'wechat': 'templates/qq/ui/warehouse_check.png'}, name='warehouse_check')
WAREHOUSE_GOTO_SEED = Button(area={'qq': (306, 128, 360, 154), 'wechat': (306, 128, 360, 154)}, color={'qq': (204, 147, 112), 'wechat': (204, 147, 112)}, button={'qq': (306, 128, 360, 154), 'wechat': (306, 128, 360, 154)}, file={'qq': 'templates/qq/ui/warehouse_goto_seed.png', 'wechat': 'templates/qq/ui/warehouse_goto_seed.png'}, name='warehouse_goto_seed')
WAREHOUSE_SEED_CHECK = Button(area={'qq': (302, 126, 363, 156), 'wechat': (302, 126, 363, 156)}, color={'qq': (226, 171, 107), 'wechat': (226, 171, 107)}, button={'qq': (302, 126, 363, 156), 'wechat': (302, 126, 363, 156)}, file={'qq': 'templates/qq/ui/warehouse_seed_check.png', 'wechat': 'templates/qq/ui/warehouse_seed_check.png'}, name='warehouse_seed_check')
WIKI_CHECK = Button(area={'qq': (244, 72, 298, 98), 'wechat': (244, 72, 298, 98)}, color={'qq': (233, 206, 186), 'wechat': (233, 206, 186)}, button={'qq': (244, 72, 298, 98), 'wechat': (244, 72, 298, 98)}, file={'qq': 'templates/qq/ui/wiki_check.png', 'wechat': 'templates/qq/ui/wiki_check.png'}, name='wiki_check')

ASSET_NAME_TO_CONST = {
    'btn_background_tree': BTN_BACKGROUND_TREE,
    'btn_batch_sell': BTN_BATCH_SELL,
    'btn_claim': BTN_CLAIM,
    'btn_claim_task': BTN_CLAIM_TASK,
    'btn_claim_yellow': BTN_CLAIM_YELLOW,
    'btn_click_to_close': BTN_CLICK_TO_CLOSE,
    'btn_close': BTN_CLOSE,
    'btn_come_again': BTN_COME_AGAIN,
    'btn_confirm': BTN_CONFIRM,
    'btn_crop_maturity_time_suffix': BTN_CROP_MATURITY_TIME_SUFFIX,
    'btn_crop_removal': BTN_CROP_REMOVAL,
    'btn_direct_claim': BTN_DIRECT_CLAIM,
    'btn_expand': BTN_EXPAND,
    'btn_expand_brand': BTN_EXPAND_BRAND,
    'btn_expand_check': BTN_EXPAND_CHECK,
    'btn_expand_confirm': BTN_EXPAND_CONFIRM,
    'btn_expand_direct_confirm': BTN_EXPAND_DIRECT_CONFIRM,
    'btn_farming': BTN_FARMING,
    'btn_fertilizer_use_confirm': BTN_FERTILIZER_USE_CONFIRM,
    'btn_friend_agreed': BTN_FRIEND_AGREED,
    'btn_friend_apply': BTN_FRIEND_APPLY,
    'btn_friend_right_frame': BTN_FRIEND_RIGHT_FRAME,
    'btn_grass': BTN_GRASS,
    'btn_grass_end': BTN_GRASS_END,
    'btn_harvest': BTN_HARVEST,
    'btn_harvest_pop': BTN_HARVEST_POP,
    'btn_hefeng_100': BTN_HEFENG_100,
    'btn_hefeng_101': BTN_HEFENG_101,
    'btn_hefeng_102': BTN_HEFENG_102,
    'btn_hefeng_103': BTN_HEFENG_103,
    'btn_hefeng_104_s': BTN_HEFENG_104_S,
    'btn_hefeng_105_s': BTN_HEFENG_105_S,
    'btn_hefeng_106': BTN_HEFENG_106,
    'btn_hefeng_107': BTN_HEFENG_107,
    'btn_hefeng_108': BTN_HEFENG_108,
    'btn_home': BTN_HOME,
    'btn_land_left': BTN_LAND_LEFT,
    'btn_land_pop_empty': BTN_LAND_POP_EMPTY,
    'btn_land_right': BTN_LAND_RIGHT,
    'btn_land_right_2': BTN_LAND_RIGHT_2,
    'btn_land_upgrade_check': BTN_LAND_UPGRADE_CHECK,
    'btn_land_upgrade_confirm': BTN_LAND_UPGRADE_CONFIRM,
    'btn_login_again': BTN_LOGIN_AGAIN,
    'btn_mall_free': BTN_MALL_FREE,
    'btn_mall_free_done': BTN_MALL_FREE_DONE,
    'btn_mature': BTN_MATURE,
    'btn_menu': BTN_MENU,
    'btn_monthly_card': BTN_MONTHLY_CARD,
    'btn_monthly_card_accept': BTN_MONTHLY_CARD_ACCEPT,
    'btn_monthly_card_end': BTN_MONTHLY_CARD_END,
    'btn_monthly_card_end_2': BTN_MONTHLY_CARD_END_2,
    'btn_oneclick_open': BTN_ONECLICK_OPEN,
    'btn_ordinary_fertilizer': BTN_ORDINARY_FERTILIZER,
    'btn_organic_fertilizer': BTN_ORGANIC_FERTILIZER,
    'btn_planting': BTN_PLANTING,
    'btn_qqsvip': BTN_QQSVIP,
    'btn_qqsvip_check': BTN_QQSVIP_CHECK,
    'BTN_SEED_SELECT_POPUP_RIGHT': BTN_SEED_SELECT_POPUP_RIGHT,
    'btn_share_green': BTN_SHARE_GREEN,
    'btn_share_red_point': BTN_SHARE_RED_POINT,
    'btn_share_yellow': BTN_SHARE_YELLOW,
    'btn_shop_buy_check': BTN_SHOP_BUY_CHECK,
    'btn_shop_buy_confirm': BTN_SHOP_BUY_CONFIRM,
    'btn_special_warehouse': BTN_SPECIAL_WAREHOUSE,
    'btn_steal': BTN_STEAL,
    'btn_steal_sign': BTN_STEAL_SIGN,
    'btn_steal_single': BTN_STEAL_SINGLE,
    'btn_steal_single_2': BTN_STEAL_SINGLE_2,
    'BTN_STEAL_TOTAL': BTN_STEAL_TOTAL,
    'btn_visit_first': BTN_VISIT_FIRST,
    'btn_warehouse_seed_20_empty': BTN_WAREHOUSE_SEED_20_EMPTY,
    'btn_withered': BTN_WITHERED,
    'friend_check': FRIEND_CHECK,
    'icon_farming_in_friend_list': ICON_FARMING_IN_FRIEND_LIST,
    'icon_guard_dog': ICON_GUARD_DOG,
    'icon_item_locked': ICON_ITEM_LOCKED,
    'icon_land_amethyst': ICON_LAND_AMETHYST,
    'icon_land_black': ICON_LAND_BLACK,
    'icon_land_gold': ICON_LAND_GOLD,
    'icon_land_gold_2': ICON_LAND_GOLD_2,
    'icon_land_red': ICON_LAND_RED,
    'icon_land_stand': ICON_LAND_STAND,
    'icon_land_upgrade': ICON_LAND_UPGRADE,
    'icon_num_0': ICON_NUM_0,
    'icon_num_1': ICON_NUM_1,
    'icon_num_2': ICON_NUM_2,
    'icon_num_3': ICON_NUM_3,
    'icon_num_4': ICON_NUM_4,
    'icon_num_5': ICON_NUM_5,
    'icon_num_6': ICON_NUM_6,
    'icon_num_7': ICON_NUM_7,
    'icon_num_8': ICON_NUM_8,
    'icon_num_9': ICON_NUM_9,
    'icon_num_left': ICON_NUM_LEFT,
    'icon_seed_locked': ICON_SEED_LOCKED,
    'icon_steal_in_friend_detail': ICON_STEAL_IN_FRIEND_DETAIL,
    'icon_steal_in_friend_list': ICON_STEAL_IN_FRIEND_LIST,
    'mail_check': MAIL_CHECK,
    'main_goto_friend': MAIN_GOTO_FRIEND,
    'main_goto_mall': MAIN_GOTO_MALL,
    'main_goto_menu': MAIN_GOTO_MENU,
    'main_goto_pet': MAIN_GOTO_PET,
    'main_goto_share': MAIN_GOTO_SHARE,
    'main_goto_shop': MAIN_GOTO_SHOP,
    'main_goto_skin': MAIN_GOTO_SKIN,
    'main_goto_task': MAIN_GOTO_TASK,
    'main_goto_warehouse': MAIN_GOTO_WAREHOUSE,
    'main_goto_wiki': MAIN_GOTO_WIKI,
    'mall_check': MALL_CHECK,
    'mall_check_2': MALL_CHECK_2,
    'mall_goto_main': MALL_GOTO_MAIN,
    'menu_check': MENU_CHECK,
    'menu_goto_mail': MENU_GOTO_MAIL,
    'menu_goto_main': MENU_GOTO_MAIN,
    'pet_check': PET_CHECK,
    'seed_btn_colored_glaze_lotus': SEED_BTN_COLORED_GLAZE_LOTUS,
    'seed_btn_haha_pumpkin': SEED_BTN_HAHA_PUMPKIN,
    'seed_btn_heart_fruit': SEED_BTN_HEART_FRUIT,
    'seed_btn_mugwort': SEED_BTN_MUGWORT,
    'setting_check': SETTING_CHECK,
    'share_check': SHARE_CHECK,
    'shop_check': SHOP_CHECK,
    'skin_check': SKIN_CHECK,
    'task_check': TASK_CHECK,
    'warehouse_check': WAREHOUSE_CHECK,
    'warehouse_goto_seed': WAREHOUSE_GOTO_SEED,
    'warehouse_seed_check': WAREHOUSE_SEED_CHECK,
    'wiki_check': WIKI_CHECK,
}
